// <auto-generated />
using Chest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Chest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180421010518_CreateSchema")]
    partial class CreateSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Chest.Data.KeyValueData", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("key")
                        .HasMaxLength(100);

                    b.Property<string>("SerializedData")
                        .HasColumnName("serialized_data")
                        .HasMaxLength(4096);

                    b.HasKey("Key");

                    b.ToTable("key_value_data");
                });
#pragma warning restore 612, 618
        }
    }
}
