// Copyright (c) 2019 Lykke Corp.
// See the LICENSE file in the project root for more information.

// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Chest.Client.AutorestClient
{
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// Chest API
    /// </summary>
    public partial interface IChestClient : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Gets the IMetadata.
        /// </summary>
        IMetadata Metadata { get; }

        /// <summary>
        /// Gets the IRoot.
        /// </summary>
        IRoot Root { get; }

    }
}
